CLIENT_NAME = "Terraria230"

CONNECT = 1
DISCONNECT = 2
SET_USER_SLOT = 3
PLAYER_INFO = 4
PLAYER_INVENTORY_SLOT = 5
REQUEST_WORLD_DATA = 6
WORLD_INFO = 7
REQUEST_ESSENTIAL_TILES = 8
STATUS = 9
SEND_SECTION = 10
SECTION_TILE_FRAME = 11
SPAWN_PLAYER = 12
UPDATE_PLAYER = 13


CLIENT_UUID = 68
PLAYER_HP = 16
PLAYER_MANA = 42

